### PR TITLE
Completed All Serial Numbers

### PR DESCRIPTION
**Pull request by saloni-garg**

### CODE REVIEW

**Comment by GeorgLink** [comment]
Thanks @saloni-garg 

I like the idea of serial numbers. Just to clarify, I might have missed something: What need do the serial numbers satisfy?

I have concerns in the context of these metrics. The list of metrics is in constant evolution and under active development. Assigning serial numbers means that as metrics get added or removed, we will have gaps and non-alphabetical serial ordering. Using the serial numbers to reference metrics adds a layer of abstraction that removes the user one step from the metric definitions.

A practical question: as we change metric definitions, do we need to give a metric a new serial number to represent the change?

**Comment by germonprez** [comment]
I have to agree on this. I'm not really sure of the utility of these.

**Comment by GeorgLink** [comment]
Thanks @BenLloydPearson and @germonprez for the feedback.

@saloni-garg could you help us understand what sparked the idea for this pull request?

**Comment by saloni-garg** [comment]
Actually, I was working on [issue #61](https://github.com/chaoss/metrics/issues/61) and wished to point three tuples from the table that seemed duplicates, but couldn't find a way to pin point those three. 
So the main reason which made me suggest adding serial numbers, was ease of pointing out a specific metric.

**Comment by GeorgLink** [comment]
@saloni-garg thanks for clarifying. #61 certainly needs some work. 
Could you use the "Name" that is given to metrics for referencing them? 
I know that it is not as elegant as a serial number, but it is more flexible in the long-term.

**Comment by saloni-garg** [comment]
Okay, @GeorgLink. I understand serial numbers may pose a problem in the later times. I'll try to use names for pointing out the issues in #61 now :)

**Pull request closed without merging**
