### PR TITLE
Added activity metric information for Total contributors

### PR DESCRIPTION
**Pull request by a-hodges**

### CODE REVIEW

**Comment by b-hodges** [comment]
total-contributors

**Comment by b-hodges** [comment]
The schema is referenced as GHTorrent in the document.
I've also updated the image URL to work.

**Comment by GeorgLink** [comment]
>The schema is referenced as GHTorrent in the document.
I cannot find it. What line number is this on?

>I've also updated the image URL to work.
The image does not show a graph. Is it a linechart or columnchart?  Is there a better - more interesting - screenshot with data?

**Comment by b-hodges** [comment]
GHTorrent is mentioned on line 16 of the total-contributers.md document.
And I can't seem to find a better example of the graph (which should be a line graph). Anything I try results in an empty graph. It's possible that it's broken right now, but I can't tell.

**Comment by GeorgLink** [comment]
Since it is GHTorrent, maybe you could link to the schema description: http://ghtorrent.org/relational.html

The graph, if it does not show anything, then maybe not include the picture but describe that it is a line graph with axis descriptions.

**Pull request merged**
