### PR TITLE
Added activity metric: Followers

### PR DESCRIPTION
**Pull request by b-hodges**
Based on the GHTorrent database

### CODE REVIEW

**Comment by germonprez** [comment]
Could you also remove the GitHub reference. The goal in these metrics is to maintain an agnostic-ness to them. The specific references will show up via the known implementations.

**Comment by germonprez** [comment]
Also, is this implemented on GHData? If so, please add it as a known implementation

**Comment by b-hodges** [comment]
The GitHub reference is based on the `Stars: Number of stars (GitHub)` metric.
And the metric is available in the GHTorrent database, but doesn't appear to be implemented in GHData.

**Comment by GeorgLink** [comment]
I don't know that we would have a more generic metric to include this under.

I agree with @b-hodges that it is difficult to not mention GitHub for this metric, since the concept Follower is directly from GitHub. We can make it more generic at a future time, when we figure out how.

@b-hodges can you include a link to the GHTorrent schema please?

**Comment by b-hodges** [comment]
Done

**Pull request merged**
