### PR TITLE
Changed contribution link in Readme.md

### PR DESCRIPTION
**Pull request by Satyam-Bhalla**
Link to the contribution page gives Not found.Changed to the accurate link

### CODE REVIEW

**Comment by GeorgLink** [comment]
We have a contributing file, can you please link to it: .github/CONTRIBUTING.md

The file proposed in this pull request is a metrics detail page.

**Comment by jgbarah** [comment]
@GeorgLink had not realized we had that `.github` directory. Wouldn't it be better having `CONTRIBUTING.md` in the main directory instead, so that it is more clearly prominent?

**Comment by GeorgLink** [comment]
We moved the contributing.md to the .github directory because it declutters
the repository but still provides the GitHub features around having the
contributing.md file.

We should link to the contributing.md file from the README.md, which this
pull request is about.

**Comment by jgbarah** [comment]
> We moved the contributing.md to the .github directory because it declutters the repository but still provides the GitHub features around having the contributing.md file.

If you feel it is better to have it that way, please go ahead. I was just curious, because I think it is customary to look for the `CONTRIBUTING.md` file in the root of the repo. But In understand your concerns, so no problem from my side.

**Comment by GeorgLink** [comment]
Thanks @Satyam-Bhalla

**Pull request merged**
