### PR TITLE
Contributor activity level

### PR DESCRIPTION
**Pull request by amunz**

### CODE REVIEW

**Comment by amunz** [comment]
Added contributor activity activity metric.

**Comment by amunz** [comment]
Please check out the changes.

**Comment by GeorgLink** [comment]
Thanks @amunz 

Can you please remove the template text from the Formula section?

**Comment by GeorgLink** [comment]
Thanks for the changes

**Comment by GeorgLink** [comment]
Thanks @amunz 
Merging with lazy consensus achieved.

**Pull request merged**
