### PR TITLE
Create pull-requests-over-time.md

### PR DESCRIPTION
**Pull request by Illuminatian**
Addition of a new metric for the list.

### CODE REVIEW

**Comment by GeorgLink** [comment]
Thanks @Illuminatian 

The detail page that @rpaik references is https://github.com/chaoss/metrics/blob/master/activity-metrics/code-commits.md
Can you please add your work as a 'sample implementation'

**Comment by germonprez** [comment]
Thanks for this. Can you just put a link to GL in the known implementations (less text -- just the link)

**Comment by Illuminatian** [comment]
Added Grimoire Lab to list of known implementations.

**Comment by Illuminatian** [comment]
Made requested change to remove default text

**Comment by Illuminatian** [comment]
Added change to activity metrics list as requested by @GeorgLink

**Comment by GeorgLink** [comment]
Thanks @Illuminatian 
Merging with lazy consensus achieved.

**Pull request merged**
