### PR TITLE
Added metric info for Contributor gender

### PR DESCRIPTION
**Pull request by b-hodges**
From GHData

### CODE REVIEW

**Comment by GeorgLink** [comment]
If there is no display, is the metric used elsewhere?

**Comment by b-hodges** [comment]
The metric is available via the API, but the frontend doesn't appear to have a component to display it yet.

**Comment by GeorgLink** [comment]
Great, thanks!

**Comment by GeorgLink** [comment]
Thanks @b-hodges 
Merging with lazy consensus achieved.

**Pull request merged**
