### PR TITLE
Create metrics table

### PR DESCRIPTION
**Pull request by klumb**
In an effort to make the metrics more consumable for tooling, I created this HTML table. If this is acceptable, I will create one for the remaining metrics pages.

I went with HTML on this because it allows for row spanning which I believe allows us to visualize the relationships between the lower level metrics and aggregate them into high-level metrics.

### CODE REVIEW

**Comment by GeorgLink** [comment]
Hi @klumb ,
Thank you for this initiative. I think the table structure looks great but I am not a tooling person. 

Maybe you could send a message to the mailing lists (metrics and software), include a link to this pull request, and ask for feedback from people who will actually consume the document.

Once the table is build out to your satisfaction, we can merge in the pull request.

**Comment by jgbarah** [comment]
I like the idea. But maybe it would be better to write the table in Markdown? (just for consistency with the rest of the document).

**Comment by germonprez** [comment]
What are the options outside of HTML?

**Comment by npch** [comment]
Github Flavoured Markdown supports tables, but not (AFAIK) merged cells, so it would look like this:

```
Metric | Signal | Action
--- | --- | ---
Value Accumulation | Bug Resolution | Tickets Closed = Time from bug opened to bug closed
Value Accumulation | Bug Resolution | Time to Close = Total # of tickets closed
Value Accumulation | Patch Speed | Time to Merge = Time from submission to merge or abandon
Value Accumulation | Patch Speed | Review Efficiency = # of merged patches / # of abandoned patches
Community Growth | # of new developers | New Contributors = # of first time contributors over time
Community Growth | # of new developers | ...
```

Metric | Signal | Action
--- | --- | ---
Value Accumulation | Bug Resolution | Tickets Closed = Time from bug opened to bug closed
Value Accumulation | Bug Resolution | Time to Close = Total # of tickets closed
Value Accumulation | Patch Speed | Time to Merge = Time from submission to merge or abandon
Value Accumulation | Patch Speed | Review Efficiency = # of merged patches / # of abandoned patches
Community Growth | # of new developers | New Contributors = # of first time contributors over time
Community Growth | # of new developers | ...

**Comment by sgoggins** [comment]
I am not following exactly what this is .... The term metric is now at a high level of abstraction, and signal is more granular. Action then sounds like a specifically measurable item that we had previously been calling a "metric."

I like the idea of separating layers, but I am concerned that right now this commits us to a language about what each "thing" means that has not yet been sorted out.

What I would like to see is a set of 3-7 specific, measurable items identified for a pilot cycle through the various software implementations.  From that I think we can start to figure out what the right words and layers are ... This is helpful, but I want to build something off of a list of "things to build" without making a commitment to what we call them just yet. 

In this paper I describe how making commitments to what we call things too soon can cause a lot of confusion for along time on social computing projects ... https://goo.gl/info/ypuKzJ

**Comment by klumb** [comment]
Thanks, I do think markdown is the better way to go here, I only went with HTML because it allowed me to display the table the way I visualized it based on the current discussion in the markdown file.  

@goggins, your comment is very helpful. What does tooling want to see here?

**Comment by sgoggins** [comment]
image

**Comment by sgoggins** [comment]
@klumb : see my comment above and let me know if it helps. I do not speak for the software committee, but only for my thoughts as a member of the software committee.

**Comment by GeorgLink** [comment]
Reposting my response from the mailing list to keep the discussion together:

Quick feedback based on my undestanding:
 

>  Our framing to date has been:
>
> Metric Category (Growth, Maturity & Decline, for example)
> Metric (Tickets Closed, for example).


I always thought of "activity metric" as the counter part to (component of) what you call "metric category".

 

> The proposed change to our framing looks sort of like this:
>
> Metric Category
> - “Metric” (Value accumulation, for example)
> - “Signal” (Bug Resolution, for example)
> - “Action” (Tickets Closed, for example)
>
>
>  Here’s my concern, and its not really a concern that is conceptual, but instead procedural, or wishing to guide how we iterate on the things we encase in software construction. As principles:
>
> 1. I think we know that the lowest level of abstraction needs to be something implemented in code.


Agreed. 

For this reason, I don't think the framing of metric - signal - action is appropriate for understanding these levels of abstractions.

I propose an understand the terms that is independent of metric aggregation:
- metric is independent of level of abstraction (could be composit or raw activity metric) [example: average time to close issue is increasing month over month];
- signal is merely how the metric can be interpreted [example: contributors are submitting issues faster than maintainers can close them];
- action is the response to the (metric informed) signal [example: promote more contributors to maintainers to spread the load of responding to and closing issues].

With this understanding, we need to ignore signal and action for now and focus solely on metric - which is the only aspect relevant to implementation for now.

 

> 2. I think we know that the metric category is a bucket for collecting things implemented in code into groups that make sense to both the metrics and software committees.


Agreed.

I think Kevin was proposing a way to show these "buckets" and what they contain, including the "layers of subcategories".
 

> 3. Its also likely that there will be layers of subcategories and groupings in between the coarsest (metrics category) and most granular (discrete measurable items or “activity metrics” like ‘Tickets closed’).   
>
> I propose that;
> - We identify the layers in between through an actual implementation of 3-7 “activity metrics” or “measurable items” like ‘tickets closed’ in different software against possibly different repository types.
>  - From that working iteration cycle, we then come back and try to identify how the “activity metrics” or “measurable items” might be grouped together to inform subcategories or subgroupings of “growth, maturity and decline” (a metrics category, for example.).  

Sounds like a good approach.

Does this mean we go back to what we used to have on the wiki, only with fewer (3-7) activity metrics for each of the four highest-level metrics. During the implementation process, I would expect to learn whether these activity metrics are actually at the lowest level (measurable item?) or composite metrics (which introduces a layer).

**Comment by jgbarah** [comment]
@klumb said:

> What does tooling want to see here?

I think, at least from the GrimoireLab side, we don't have a preference here. In our standard dashboard metrics are now grouped by data source, but other arrangements are possible, and one based on "what do metrics mean" seems quite reasonable to me.

**Comment by germonprez** [comment]
In response to the table above and based on today's Google Hangout.

1) Remove two leftmost columns. 
2) Rename Action column as Activity Metic

This will remove any predefined associations and hone in on 3-7 activity metrics that can be used to define specific metrics.

**Comment by klumb** [comment]
I have updated the table of Growth-Maturity-Decline and added tables for the remaining metrics. The activity metrics I have inserted into the tables are taken directly from the metrics discussions occurring in the markdown pages.

**Comment by germonprez** [comment]
I'd say go ahead and merge this. We can start a new request to tweak the language.

**Comment by GeorgLink** [comment]
Thanks for the review @germonprez

**Comment by rpaik** [comment]
Just a quick comment (sorry I've been absent as I've been traveling....)

I like the simplified table we have with 2 columns.  At some point, would it make sense to add a third column to note if any of the metrics are already implemented in the software?  We could just say Y/N with a link to a repo if there's an implementation in the Software committee repo.

**Comment by germonprez** [comment]
Good idea :)

**Pull request merged**
