### PR TITLE
Added activity metric information for Pony factor

### PR DESCRIPTION
**Pull request by b-hodges**

### CODE REVIEW

**Comment by germonprez** [comment]
Is this bus factor? The same as pony factor?

**Comment by b-hodges** [comment]
@germonprez This is listed in GHData as the bus factor, but follows the math outlined as Pony Factor here.

**Comment by b-hodges** [comment]
@GeorgLink There doesn't seem to be a visualization in GHData's frontend, even though the code for the calculations is on the backend.

**Comment by GeorgLink** [comment]
1) We should be clear about 'Bus Factor' vs. 'Pony Factor'. They are related but different. Can you work with GHData/Augur to clarify and fix the naming (e.g., open issue).

2) How is the metric exposed to the user if there is no visualization? Visualization can be a number, it does not have to be a graph.

**Comment by b-hodges** [comment]
I can't comment on the difference between bus factor and pony factor, but I have created a sample visualization for the metric as used by Augur (hence the bus factor naming)
capture

**Pull request merged**
